services:
  web-youtube:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL
    container_name: web-youtube
    ports:
      - "3012:3000"
    restart: unless-stopped
    networks:
      - web-youtube-network

networks:
  web-youtube-network:
    driver: bridge
